PATHTOROOT = ../../../..

OBJS =	BrowserPaneChangeEvent.class \
	FrameSelectionChangeEvent.class \
	FrameSortOrderChangeEvent.class \
	RegionSelectionChangeEvent.class \
	SourceImageSelectionChangeEvent.class \
	SourceSpectrumSelectionChangeEvent.class \
	StatusChangeEvent.class \
	TaskChangeEvent.class \
	VOIFunctionChangeEvent.class \
	WellKnownContext.class \
	WindowCenterAndWidthChangeEvent.class \
	ApplyShutterChangeEvent.class \
	WindowLinearCalculationChangeEvent.class \
	WindowingAccelerationValueChangeEvent.class

all:	${OBJS}

include ${PATHTOROOT}/Makefile.common.mk

