PATHTOROOT = ../../..

OBJS =	\
	MonitoredInputStream.class \
	MonitoredOutputStream.class \
	TransferMonitor.class \
	TransferMonitoringContext.class

all:	${OBJS}

include ${PATHTOROOT}/Makefile.common.mk

